export const ERROR_CODES = [
  "CONFIG_INVALID",
  "PROJECT_NAME_INVALID",
  "UNKNOWN_INTEGRATION",
  "DUPLICATE_INTEGRATION",
  "UNSUPPORTED_CONTEXT",
  "MISSING_REQUIREMENT",
  "INTEGRATION_CONFLICT",
  "DEPENDENCY_CYCLE",
  "PREREQUISITE_MISSING",
  "PACKAGE_MANAGER_MISSING",
  "FILE_ALREADY_EXISTS",
  "FILE_MUTATION_FAILED",
  "COMMAND_FAILED",
  "VERIFICATION_FAILED",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
