import { TASK_ERROR_CODES } from "../tasks/errors.js";

export const ERROR_CODES = [
  "CONFIG_INVALID",
  "SELECTION_INVALID",
  "RECIPE_INVALID",
  "PROJECT_NAME_INVALID",
  "UNKNOWN_INTEGRATION",
  "DUPLICATE_INTEGRATION",
  "UNSUPPORTED_CONTEXT",
  "MISSING_REQUIREMENT",
  "INTEGRATION_CONFLICT",
  "DEPENDENCY_CYCLE",
  "PLAN_INVALID",
  "PREREQUISITE_MISSING",
  "PROJECT_NOT_FOUND",
  "PACKAGE_MANAGER_MISSING",
  "LOCKFILE_CONFLICT",
  "FILE_ALREADY_EXISTS",
  "FILE_MUTATION_FAILED",
  "EXECUTION_LOCKED",
  "EXECUTION_ABORTED",
  "COMMAND_TIMED_OUT",
  "COMMAND_FAILED",
  "VERIFICATION_FAILED",
  "INTENDED_CONTEXT_MISMATCH",
  "INTENDED_DEPENDENCY_MISSING",
  "INTENDED_VERIFICATION_FAILED",
  ...TASK_ERROR_CODES,
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
