import type { RepoSetupError } from "@reposetup/core";

export const EXIT_CODES = {
  SUCCESS: 0,
  GENERAL_FAILURE: 1,
  INVALID_INPUT: 2,
  RESOLUTION_FAILURE: 3,
  PREREQUISITE_MISSING: 4,
  VERIFICATION_FAILURE: 5,
} as const;

export type ExitCode = (typeof EXIT_CODES)[keyof typeof EXIT_CODES];

const EXIT_CODE_BY_ERROR = {
  CONFIG_INVALID: EXIT_CODES.INVALID_INPUT,
  RECIPE_INVALID: EXIT_CODES.INVALID_INPUT,
  PROJECT_NAME_INVALID: EXIT_CODES.INVALID_INPUT,
  UNKNOWN_INTEGRATION: EXIT_CODES.INVALID_INPUT,
  DUPLICATE_INTEGRATION: EXIT_CODES.INVALID_INPUT,
  UNSUPPORTED_CONTEXT: EXIT_CODES.RESOLUTION_FAILURE,
  MISSING_REQUIREMENT: EXIT_CODES.RESOLUTION_FAILURE,
  INTEGRATION_CONFLICT: EXIT_CODES.RESOLUTION_FAILURE,
  DEPENDENCY_CYCLE: EXIT_CODES.RESOLUTION_FAILURE,
  PLAN_INVALID: EXIT_CODES.RESOLUTION_FAILURE,
  PREREQUISITE_MISSING: EXIT_CODES.PREREQUISITE_MISSING,
  PROJECT_NOT_FOUND: EXIT_CODES.INVALID_INPUT,
  PACKAGE_MANAGER_MISSING: EXIT_CODES.PREREQUISITE_MISSING,
  LOCKFILE_CONFLICT: EXIT_CODES.RESOLUTION_FAILURE,
  FILE_ALREADY_EXISTS: EXIT_CODES.GENERAL_FAILURE,
  FILE_MUTATION_FAILED: EXIT_CODES.GENERAL_FAILURE,
  EXECUTION_LOCKED: EXIT_CODES.GENERAL_FAILURE,
  EXECUTION_ABORTED: EXIT_CODES.GENERAL_FAILURE,
  COMMAND_TIMED_OUT: EXIT_CODES.GENERAL_FAILURE,
  COMMAND_FAILED: EXIT_CODES.GENERAL_FAILURE,
  VERIFICATION_FAILED: EXIT_CODES.VERIFICATION_FAILURE,
} as const;

export function exitCodeForError(error: RepoSetupError): ExitCode {
  return EXIT_CODE_BY_ERROR[error.code];
}

export function exitCodeForErrors(errors: readonly RepoSetupError[]): ExitCode {
  if (errors.length === 0) {
    return EXIT_CODES.GENERAL_FAILURE;
  }

  return errors.reduce<ExitCode>((highest, error) => {
    const next = exitCodeForError(error);
    return next > highest ? next : highest;
  }, EXIT_CODES.INVALID_INPUT);
}
