import type { BeginnerCatalog } from "@reposetup/core";
import { REGISTRY_REVISION, qualifiedDirectVersions } from "./qualified-versions.js";

const evidence =
  "docs/specification-documentation/implementing-docs/IMPLEMENTATION_STATUS.md#phase-25-progress--2026-09-24";
const limitations =
  "Qualified packed create/add and selection handoff only for these React/Vite, Express and FastAPI contexts on Node 24 (Python 3.12/3.13 for FastAPI). No database or deployment is included; 0.3.0 is not released.";
export const BEGINNER_CATALOG: BeginnerCatalog = {
  schemaVersion: 1,
  revision: "0.3.0-cli.4",
  recipeRevision: REGISTRY_REVISION,
  directVersions: {
    ...qualifiedDirectVersions([
      "react-vite",
      "express",
      "fastapi",
      "zod",
      "vitest",
      "prettier",
      "pydantic",
      "pytest",
      "ruff",
    ]),
    // pnpm create vite@8.3.0 invokes create-vite, whose frozen template uses
    // ranges for application packages. These are declarations, not exact installs.
    "react-vite": ["create-vite@8.3.0", "react@^19.2.0", "react-dom@^19.2.0", "vite@^7.3.1"],
  },
  cliContract: "selection-v1",
  contexts: [
    {
      id: "react-vite-ts-pnpm",
      context: {
        runtimeId: "node",
        frameworkId: "react-vite",
        packageManager: "pnpm",
        typescript: true,
      },
      optionalIds: ["zod", "vitest", "prettier"],
      evidence,
      limitations,
    },
    {
      id: "express-ts-pnpm",
      context: {
        runtimeId: "node",
        frameworkId: "express",
        packageManager: "pnpm",
        typescript: true,
      },
      optionalIds: ["zod", "vitest", "prettier"],
      evidence,
      limitations,
    },
    {
      id: "fastapi-uv",
      context: { runtimeId: "python", frameworkId: "fastapi", packageManager: "uv" },
      optionalIds: ["pydantic", "pytest", "ruff"],
      evidence,
      limitations,
    },
  ],
  guidance: [
    {
      id: "react-vite",
      purpose: "Build a browser interface with React and Vite's development/build tools.",
      when: "Choose this when your project needs an interactive browser UI.",
      unnecessary: "A server-only API does not need React.",
      example: "An interactive task list.",
      prerequisites: "Node 24 and pnpm; TypeScript starter in this catalog.",
      alternatives: "Express or FastAPI serve APIs rather than browser components.",
      impact: "Scaffolds a new application and installs its dependencies; create only.",
      goals: ["browser interface", "frontend"],
      documentationUrl: "https://vite.dev/guide/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "express",
      purpose: "Handle HTTP requests in a Node.js API.",
      when: "Choose this when a JavaScript/TypeScript backend needs routes.",
      unnecessary: "A browser-only application does not need a separate API server.",
      example: "A route returning a task list as JSON.",
      prerequisites: "Node 24 and pnpm; TypeScript starter in this catalog.",
      alternatives: "FastAPI is the Python API journey.",
      impact: "Creates API source, package scripts, and TypeScript configuration; create only.",
      goals: ["api", "http routes", "backend"],
      documentationUrl: "https://expressjs.com/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "fastapi",
      purpose: "Build a Python HTTP API using type-based request models.",
      when: "Choose this when your backend uses Python.",
      unnecessary: "A browser-only interface does not need an API framework.",
      example: "An endpoint returning a health response.",
      prerequisites: "Python 3.12/3.13 and uv 0.12.17; install prerequisites yourself.",
      alternatives: "Express is the TypeScript API journey.",
      impact: "Initializes a Python project and creates API source; create only.",
      goals: ["python api", "backend"],
      documentationUrl: "https://fastapi.tiangolo.com/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "zod",
      purpose: "Validate untrusted values against an explicit schema.",
      when: "Add it when form or API input needs runtime checks.",
      unnecessary: "Skip it when you have no input boundary to validate yet.",
      example: "Reject a task title that is not a string.",
      prerequisites: "A supported Node application.",
      alternatives: "Existing explicit validation; Pydantic for Python.",
      impact: "Adds the Zod dependency; write your own schemas.",
      goals: ["validate input", "form validation"],
      documentationUrl: "https://zod.dev/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "vitest",
      purpose: "Run repeatable assertions to catch regressions.",
      when: "Add it when application behavior needs automated tests.",
      unnecessary: "Skip a second test runner if your current one already meets your needs.",
      example: "Assert an API health response or a small React helper.",
      prerequisites: "A supported Node application and Node 24.",
      alternatives: "Keep an existing test runner.",
      impact:
        "Adds dev dependencies, a config, a test script, and context-specific samples. Existing files/scripts are preserved on add.",
      goals: ["test an app", "testing", "regressions"],
      documentationUrl: "https://vitest.dev/guide/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "prettier",
      purpose: "Apply consistent code formatting automatically.",
      when: "Add it when manual style decisions slow you down.",
      unnecessary: "Skip it if your project already has a formatter you want to keep.",
      example: "Format source consistently before review.",
      prerequisites: "A supported Node application.",
      alternatives: "Keep an existing formatter; Ruff for Python.",
      impact:
        "Adds a dev dependency, .prettierrc, and .prettierignore. Existing target files are preserved on add.",
      goals: ["format code", "formatting"],
      documentationUrl: "https://prettier.io/docs/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "pydantic",
      purpose: "Define Python data models with validation.",
      when: "Use it when Python input needs explicit data shapes.",
      unnecessary: "FastAPI already brings Pydantic; a separate selection is often unnecessary.",
      example: "Validate the fields of an API request model.",
      prerequisites: "FastAPI/uv in this catalog.",
      alternatives: "Existing manual validation; Zod for TypeScript.",
      impact: "Declares the Pydantic dependency; creates no custom models.",
      goals: ["validate input", "python models"],
      documentationUrl: "https://docs.pydantic.dev/latest/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "pytest",
      purpose: "Run Python assertions as an automated test suite.",
      when: "Add it when API behavior needs regression checks.",
      unnecessary: "Skip a second runner when your existing test suite is sufficient.",
      example: "Assert the generated FastAPI endpoint response.",
      prerequisites: "FastAPI/uv in this catalog.",
      alternatives: "Keep an existing Python test runner.",
      impact:
        "Adds pytest and the recipe's FastAPI test dependencies/sample; preserves existing sample files on add.",
      goals: ["test an app", "python testing"],
      documentationUrl: "https://docs.pytest.org/en/stable/",
      reviewedAt: "2026-10-03",
    },
    {
      id: "ruff",
      purpose: "Check Python source for lint issues and format it.",
      when: "Add it when you need consistent Python checks.",
      unnecessary: "Skip it when an existing linter/formatter covers your needs.",
      example: "Find an unused import before review.",
      prerequisites: "FastAPI/uv in this catalog.",
      alternatives: "Keep your current Python lint/format tools.",
      impact: "Adds the Ruff dependency; run checks deliberately.",
      goals: ["format code", "python linting"],
      documentationUrl: "https://docs.astral.sh/ruff/",
      reviewedAt: "2026-10-03",
    },
  ],
  presets: [
    {
      id: "beginner-react-vite",
      name: "Minimal React/Vite",
      outcome: "A small browser application without optional libraries.",
      audience: "Beginners building a browser interface.",
      contextId: "react-vite-ts-pnpm",
      kind: "starter",
      support: "candidate",
      config: {
        schemaVersion: 1,
        project: { name: "my-frontend", path: "my-frontend" },
        runtime: { id: "node" },
        packageManager: "pnpm",
        framework: { id: "react-vite", options: { typescript: true } },
        integrations: [],
      },
      reasons: { "react-vite": "Provides the browser application scaffold." },
    },
    {
      id: "beginner-express",
      name: "Minimal Express API",
      outcome: "A TypeScript API without a database or optional tools.",
      audience: "Beginners building a Node API.",
      contextId: "express-ts-pnpm",
      kind: "starter",
      support: "candidate",
      config: {
        schemaVersion: 1,
        project: { name: "my-api", path: "my-api" },
        runtime: { id: "node" },
        packageManager: "pnpm",
        framework: { id: "express", options: { typescript: true } },
        integrations: [],
      },
      reasons: { express: "Provides HTTP routes and a runnable API scaffold." },
    },
    {
      id: "beginner-fastapi",
      name: "Minimal FastAPI",
      outcome: "A Python API without persistence or optional tools.",
      audience: "Beginners building a Python API.",
      contextId: "fastapi-uv",
      kind: "starter",
      support: "candidate",
      config: {
        schemaVersion: 1,
        project: { name: "my-python-api", path: "my-python-api" },
        runtime: { id: "python" },
        packageManager: "uv",
        framework: { id: "fastapi" },
        integrations: [],
      },
      reasons: { fastapi: "Provides the Python API scaffold and its required dependencies." },
    },
  ],
};
