import {
  detectedResult,
  evidence,
  notDetected,
  type DetectionContext,
  type DetectionResult,
  type PlanContext,
  type VerificationContext,
  type VerificationResult,
} from "@reposetup/core";

import { defineIntegration } from "./define.js";
import { firstExistingPath } from "./first-existing.js";
import { hasSelectedIntegration } from "./operations.js";
import { supportsNodeOrPython } from "./python-support.js";
import { missingAnyFile } from "./verify.js";

const COMPOSE_PATHS = [
  "compose.yaml",
  "compose.yml",
  "docker-compose.yaml",
  "docker-compose.yml",
] as const;

const POSTGRES_COMPOSE = `# Generated by RepoSetup: local PostgreSQL configuration only.
# Official image environment: https://hub.docker.com/_/postgres
# Set POSTGRES_PASSWORD in a local .env before starting this service.

services:
  db:
    image: postgres:18.6
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in your local .env}
      POSTGRES_DB: \${POSTGRES_DB:-DATABASE}
    ports:
      - "127.0.0.1:\${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
`;

export const dockerComposeIntegration = defineIntegration({
  id: "docker-compose",
  name: "Docker Compose",
  category: "infrastructure",
  description: "Adds a Compose file for PostgreSQL. RepoSetup does not start containers.",
  status: "experimental",
  documentationUrl: "https://hub.docker.com/_/postgres",
  keywords: ["compose", "container", "postgres"],
  verification: { verifiedAt: "2026-09-22" },
  requirements: [
    {
      kind: "requires",
      target: { type: "integration", id: "docker" },
      reason: "Compose files are run with Docker.",
    },
    {
      kind: "requires",
      target: { type: "integration", id: "postgresql" },
      reason: "This phase writes the official PostgreSQL Compose service.",
    },
  ],
  supports(context) {
    const runtime = supportsNodeOrPython(context);
    if (!runtime.supported) {
      return runtime;
    }

    if (!context.integrationIds.includes("postgresql")) {
      return {
        supported: false,
        reason: "This phase writes Compose for PostgreSQL only.",
      };
    }

    return { supported: true };
  },
  async detect(context: DetectionContext): Promise<DetectionResult> {
    const path = await firstExistingPath(context.files, COMPOSE_PATHS);
    if (path === undefined) {
      return notDetected();
    }

    return detectedResult("certain", [evidence("file", `Found ${path}`, path)]);
  },
  plan(context: PlanContext) {
    if (!hasSelectedIntegration(context, "postgresql")) {
      return [];
    }

    return [
      {
        type: "create_file",
        path: "compose.yaml",
        content: POSTGRES_COMPOSE,
        behavior: "fail_if_exists",
        description: "Add a PostgreSQL Compose service with a localhost port and persistent volume",
      },
      {
        type: "add_env_example",
        path: ".env.example",
        entries: [
          { key: "POSTGRES_USER", placeholder: "USER" },
          { key: "POSTGRES_PASSWORD", placeholder: "PASSWORD" },
          { key: "POSTGRES_DB", placeholder: "DATABASE" },
          { key: "POSTGRES_PORT", placeholder: "5432" },
        ],
        description: "Document local PostgreSQL Compose placeholders without real credentials",
      },
      {
        type: "show_message",
        message:
          "Compose was written, but Docker and PostgreSQL were not installed or started. Create a local .env from .env.example, choose your own POSTGRES_PASSWORD, and make DATABASE_URL match the POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and POSTGRES_PORT values. Validate with docker compose config --quiet, then start Docker and run docker compose up -d db yourself. Only 127.0.0.1 is published; no database connection has been tested. See DOCKER_SETUP.md.",
        description: "Explain that Compose is not started automatically",
      },
    ];
  },
  async verify(context: VerificationContext): Promise<VerificationResult> {
    return (
      (await missingAnyFile(
        context,
        COMPOSE_PATHS,
        "a Compose file (compose.yaml or docker-compose.yml)",
      )) ?? {
        ok: true,
        message:
          "Compose configuration was found. This does not install Docker, pull images, start containers, or verify a database connection.",
      }
    );
  },
});
