export const packageName = "@reposetup/integrations" as const;

export { alembicIntegration } from "./alembic.js";
export { builtInIntegrations, createBuiltInRegistry } from "./catalog.js";
export { dockerComposeIntegration } from "./docker-compose.js";
export { dockerIntegration } from "./docker.js";
export { drizzleIntegration } from "./drizzle.js";
export { eslintIntegration } from "./eslint.js";
export { expressIntegration } from "./express.js";
export { fastapiIntegration } from "./fastapi.js";
export { fastifyIntegration } from "./fastify.js";
export { flaskIntegration } from "./flask.js";
export { githubActionsIntegration } from "./github-actions.js";
export { mongodbIntegration } from "./mongodb.js";
export { mongooseIntegration } from "./mongoose.js";
export { nextjsIntegration } from "./nextjs.js";
export { nodeIntegration } from "./node.js";
export { npmIntegration } from "./npm.js";
export { pipIntegration } from "./pip.js";
export { playwrightIntegration } from "./playwright.js";
export { pnpmIntegration } from "./pnpm.js";
export { postgresqlIntegration } from "./postgresql.js";
export { prettierIntegration } from "./prettier.js";
export { prismaIntegration } from "./prisma.js";
export { pydanticIntegration } from "./pydantic.js";
export { pytestIntegration } from "./pytest.js";
export { pythonIntegration } from "./python.js";
export { reactViteIntegration } from "./react-vite.js";
export { ruffIntegration } from "./ruff.js";
export { shadcnIntegration } from "./shadcn.js";
export { sqlalchemyIntegration } from "./sqlalchemy.js";
export { sqliteIntegration } from "./sqlite.js";
export { tailwindIntegration } from "./tailwind.js";
export { uvIntegration } from "./uv.js";
export { vitestIntegration } from "./vitest.js";
export { zodIntegration } from "./zod.js";
